Repository CleverTap/clevertap-android-sdk, pull requests merged in 2024-07, with the labels that each got.

#631 Unit tests for file type support SDK-3913
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/FileMemoryV2.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/InAppGifMemoryV1.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/InAppImageMemoryV1.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/ImpressionManagerTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/InAppQueueTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplateInAppDataTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/FileResourceProviderTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/cleanup/FileCleanupStrategyCoroutineTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/cleanup/FileCleanupStrategyExecutorsTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/memory/FileMemoryAccessObjectTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/memory/FileMemoryV2Test.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/memory/InAppGifMemoryAccessObjectV1Test.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/memory/InAppGifMemoryV1Test.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/memory/InAppImageMemoryAccessObjectV1Test.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/memory/InAppImageMemoryV1Test.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/memory/MemoryCreatorTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/preload/FilePreloaderCoroutineTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/preload/FilePreloaderExecutorsTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/preload/InAppImagePreloaderCoroutineTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/preload/InAppImagePreloaderExecutorsTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/repo/FileResourcesRepoTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/repo/InAppImageRepoTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/task/MockCTExecutors.kt
Labels: Reviewed chained PRs, core7.0.0

#636 Feature/vars file types testing
  clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapFactory.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/repo/FileResourcesRepoFactory.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/repo/FileResourcesRepoImpl.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/variables/CTVariableUtils.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/variables/CTVariables.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/variables/Var.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/variables/VarCache.java
  clevertap-core/src/test/java/com/clevertap/android/sdk/variables/CTVariablesTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/variables/ParserTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/variables/VarCacheTest.kt
  sample/src/main/java/com/clevertap/demo/ExampleVariables.java
  sample/src/main/java/com/clevertap/demo/MyApplication.kt
  sample/src/main/java/com/clevertap/demo/ui/main/FileVarsData.kt
  sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenModel.kt
  sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenViewModel.kt
Labels: core7.0.0

#625 File type support for vars feature.
  clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapFactory.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/StoreProvider.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppNotification.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppType.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/InAppController.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplateInAppData.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/data/InAppResponseAdapter.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/FileResourceProvider.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/FileMemoryAccessObject.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/FileMemoryV2.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/InAppGifMemoryAccessObjectV1.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/InAppGifMemoryV1.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/InAppImageMemoryAccessObjectV1.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/InAppImageMemoryV1.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/MemoryCreator.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/preload/FilePreloaderCoroutine.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/preload/FilePreloaderExecutors.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/preload/FilePreloaderStrategy.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/repo/FileResourcesRepo.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/repo/FileResourcesRepoFactory.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/repo/FileResourcesRepoImpl.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/response/InAppResponse.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/task/CTExecutors.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/utils/FileCache.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/variables/CTVariableUtils.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/variables/CTVariables.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/variables/Var.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/variables/VarCache.java
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/ImpressionManagerTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/InAppQueueTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplateInAppDataTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/FileResourceProviderTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/cleanup/FileCleanupStrategyCoroutineTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/cleanup/FileCleanupStrategyExecutorsTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/memory/FileMemoryAccessObjectTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/memory/FileMemoryV2Test.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/memory/InAppGifMemoryAccessObjectV1Test.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/memory/InAppGifMemoryV1Test.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/memory/InAppImageMemoryAccessObjectV1Test.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/memory/InAppImageMemoryV1Test.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/memory/MemoryCreatorTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/preload/FilePreloaderCoroutineTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/preload/FilePreloaderExecutorsTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/preload/InAppImagePreloaderCoroutineTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/preload/InAppImagePreloaderExecutorsTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/repo/FileResourcesRepoTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/repo/InAppImageRepoTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/task/MockCTExecutors.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/variables/CTVariablesTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/variables/ParserTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/variables/VarCacheTest.kt
  sample/src/main/java/com/clevertap/demo/ExampleVariables.java
  sample/src/main/java/com/clevertap/demo/MyApplication.kt
  sample/src/main/java/com/clevertap/demo/ui/main/FileVarsData.kt
  sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenModel.kt
  sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenViewModel.kt
Labels: Reviewed chained PRs, core7.0.0

#602 Fix NullPointerException caused during device id fetch SDK-3773
  clevertap-core/src/main/java/com/clevertap/android/sdk/DeviceInfo.java
Labels: core7.0.0

#593 task(SDK-3614) - Removes redundant inapps code
  clevertap-core/src/main/java/com/clevertap/android/sdk/ActivityLifeCycleManager.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/InAppController.java
  clevertap-core/src/test/java/com/clevertap/android/sdk/ActivityLifeCycleManagerTest.kt
Labels: pending release, core7.0.0

#603 task(SDK-3795) - Fixes NPE
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/InAppController.java
Labels: core7.0.0

#630 Task/sdk 3898/app launched repeated
  clevertap-core/src/main/java/com/clevertap/android/sdk/login/LoginController.java
Labels: core7.0.0

#629 Task/mc 1790/headers inapps eval incorrectly attached t
  clevertap-core/src/main/java/com/clevertap/android/sdk/Constants.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/evaluation/EvaluationManager.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/evaluation/EventAdapter.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/store/preference/InAppStore.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/network/NetworkHeadersListener.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/network/NetworkManager.java
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/evaluation/EvaluationManagerTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/store/preference/InAppStoreTest.kt
Labels: core7.0.0

#624 task(SDK-3887) - Fixes inapp image not showing when phone is rotated
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppNotification.java
Labels: core7.0.0

#635 task(SDK - 3915) - Fixes dismiss callback when inapp was rotated
  clevertap-core/src/main/java/com/clevertap/android/sdk/InAppNotificationActivity.java
Labels: core7.0.0

#621 Feature/sdk 3780/exoplayer migration
  clevertap-core/build.gradle
  clevertap-core/src/main/java/com/clevertap/android/sdk/ControllerManager.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/Utils.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/customviews/MediaPlayerRecyclerView.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/customviews/MediaPlayerRecyclerView.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppNativeInterstitialFragment.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppNotification.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppNotificationMedia.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/InAppController.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTInboxActivity.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTInboxBaseMessageViewHolder.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTInboxListViewFragment.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTInboxMessageContent.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/video/InAppVideoPlayerHandle.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/video/InboxVideoPlayerHandle.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/video/VideoLibChecker.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/video/inapps/ExoplayerHandle.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/video/inapps/Media3Handle.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/video/inbox/ExoplayerHandle.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/video/inbox/Media3Handle.kt
  gradle/libs.versions.toml
  sample/build.gradle
Labels: core7.0.0

#632 task(SDK - 3906) - Remove cross btn from five icons
  clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/TemplateRenderer.kt
  clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/content/FiveIconBigContentView.kt
  clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/content/FiveIconSmallContentView.kt
  clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/content/PendingIntentFactory.kt
  clevertap-pushtemplates/src/main/res/drawable/pt_close.png
  clevertap-pushtemplates/src/main/res/layout-v31/five_cta_collapsed.xml
  clevertap-pushtemplates/src/main/res/layout-v31/five_cta_expanded.xml
  clevertap-pushtemplates/src/main/res/layout/five_cta_collapsed.xml
  clevertap-pushtemplates/src/main/res/layout/five_cta_expanded.xml
  docs/CTPUSHTEMPLATES.md
  docs/CTPUSHTEMPLATESANDROID12.md
  templates/CTPUSHTEMPLATES.md
  templates/CTPUSHTEMPLATESANDROID12.md
Labels: ptv1.2.4

#643 task(SDK-3780) - Fix misleading logs for exoplayer
  clevertap-core/src/main/java/com/clevertap/android/sdk/video/VideoLibChecker.kt
Labels: core7.0.0

#642 task(SDK-3922) - clear variables when user switch
  clevertap-core/src/main/java/com/clevertap/android/sdk/variables/VarCache.java
Labels: core7.0.0

#639 Add downloading of files in custom template non-visual action functions
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/CTInAppNotification.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/InAppController.java
Labels: core7.0.0

#644 Close PR comments on file type support SDK-3913
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplateContext.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/FileResourceProvider.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/FileMemoryAccessObject.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/utils/FileCache.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/FileResourceProviderTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/utils/CTCachesTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/utils/FileCacheTest.kt
Labels: core7.0.0

#641 Tests/sdk 3922/variables tests
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplateContext.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/FileResourceProvider.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/FileMemoryAccessObject.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/utils/FileCache.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/customtemplates/CustomTemplateInAppDataTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/FileResourceProviderTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/utils/CTCachesTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/utils/FileCacheTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/variables/CTVariableUtilsTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/variables/CTVariablesTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/variables/ParserTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/variables/VarCacheTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/variables/VarTest.kt
Labels: core7.0.0

#647 chore(v700) : Finishing work for release v7.0.0 SDK-3782
  CHANGELOG.md
  build.gradle
  clevertap-core/consumer-rules.pro
  clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/cleanup/FileCleanupStrategy.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/cleanup/FileCleanupStrategyCoroutine.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/cleanup/FileCleanupStrategyExecutors.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/FileMemoryAccessObject.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/FileMemoryV2.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/InAppGifMemoryAccessObjectV1.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/InAppGifMemoryV1.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/InAppImageMemoryAccessObjectV1.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/InAppImageMemoryV1.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/Memory.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/MemoryAccessObject.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/MemoryConfig.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/memory/MemoryCreator.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/repo/FileResourcesRepo.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/repo/FileResourcesRepoFactory.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/repo/FileResourcesRepoImpl.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/utils/CTCaches.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/utils/Cache.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/utils/DiskMemory.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/utils/FileCache.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/memory/FileMemoryAccessObjectTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/memory/InAppGifMemoryAccessObjectV1Test.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/memory/InAppImageMemoryAccessObjectV1Test.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/utils/CTCachesTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/utils/DiskMemoryTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/utils/InMemoryLruCacheTest.kt
  gradle/libs.versions.toml
  sample/build.gradle
  templates/CTCORECHANGELOG.md
  templates/CTPUSHTEMPLATESCHANGELOG.md
  templates/CustomCodeTemplates.md
  templates/EXAMPLES.md
  templates/README.md
  templates/Variables.md
Labels: core7.0.0

#651 Feat(SDK-3936): Handles failure in fetch asset api
  clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/inapp/images/FileResourceProvider.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/FileResourceProviderTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/inapp/images/preload/FilePreloaderCoroutineTest.kt
Labels: core7.0.0
