Repository CleverTap/clevertap-android-sdk, pull requests merged in 2025-06, with the labels that each got.

#833 Task/sdk 4887/sample custom template + app_inbox
  sample/build.gradle
  sample/src/main/AndroidManifest.xml
  sample/src/main/java/com/clevertap/demo/HomeScreenActivity.kt
  sample/src/main/java/com/clevertap/demo/MyApplication.kt
  sample/src/main/java/com/clevertap/demo/ViewModelFactory.kt
  sample/src/main/java/com/clevertap/demo/WebViewActivity.kt
  sample/src/main/java/com/clevertap/demo/ui/customtemplates/CustomInterstitialViewModel.kt
  sample/src/main/java/com/clevertap/demo/ui/customtemplates/CustomInterstitialViewModelProvider.kt
  sample/src/main/java/com/clevertap/demo/ui/customtemplates/CustomTemplateDefinitions.kt
  sample/src/main/java/com/clevertap/demo/ui/customtemplates/OpenUrlConfirmDialog.kt
  sample/src/main/java/com/clevertap/demo/ui/customtemplates/OpenUrlConfirmViewModel.kt
  sample/src/main/java/com/clevertap/demo/ui/customtemplates/OpenUrlConfirmViewModelProvider.kt
  sample/src/main/java/com/clevertap/demo/ui/customtemplates/OverlayDialog.kt
  sample/src/main/java/com/clevertap/demo/ui/inbox/CustomInboxComposeActivity.kt
  sample/src/main/java/com/clevertap/demo/ui/inbox/CustomInboxScreen.kt
  sample/src/main/java/com/clevertap/demo/ui/inbox/CustomInboxViewModel.kt
  sample/src/main/java/com/clevertap/demo/ui/inbox/CustomInboxViewModelContract.kt
  sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenFragment.kt
  sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenModel.kt
  sample/src/main/java/com/clevertap/demo/ui/main/HomeScreenViewModel.kt
  sample/src/main/res/layout/home_screen_activity.xml
Labels: sampleapp

#836 Task/sdk 4940/eaa pushtempaltes
  clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/PTConstants.java
  clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/PushTemplateReceiver.java
  clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/TemplateRenderer.kt
  clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/Utils.java
  clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/content/AutoCarouselContentView.kt
  clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/content/BigImageContentView.kt
  clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/content/ContentView.kt
  clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/content/FiveIconBigContentView.kt
  clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/content/FiveIconSmallContentView.kt
  clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/content/ManualCarouselContentView.kt
  clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/content/ProductDisplayLinearBigContentView.kt
  clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/content/TimerBigContentView.kt
  clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/content/ZeroBezelBigContentView.kt
  clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/content/ZeroBezelMixedSmallContentView.kt
  clevertap-pushtemplates/src/main/java/com/clevertap/android/pushtemplates/styles/InputBoxStyle.kt
  clevertap-pushtemplates/src/main/res/layout-v31/cv_small_zero_bezel.xml
  clevertap-pushtemplates/src/main/res/layout-v31/zero_bezel.xml
  clevertap-pushtemplates/src/main/res/layout/cv_small_zero_bezel.xml
  clevertap-pushtemplates/src/main/res/layout/image_view_dynamic.xml
  clevertap-pushtemplates/src/main/res/layout/image_view_flipper_dynamic.xml
  clevertap-pushtemplates/src/main/res/layout/manual_carousel.xml
  clevertap-pushtemplates/src/main/res/layout/rating.xml
  clevertap-pushtemplates/src/main/res/layout/zero_bezel.xml
  clevertap-pushtemplates/src/main/res/values/strings.xml
  clevertap-pushtemplates/src/test/java/com/clevertap/android/pushtemplates/UtilsTest.kt
Labels: eaa

#827 SDK-4608 Test coverage
  clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapFactory.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/CoreState.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/CoreState.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/DeviceInfo.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/Utils.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/events/EventMediator.java
  clevertap-core/src/main/java/com/clevertap/android/sdk/network/NetworkRepo.kt
  clevertap-core/src/main/java/com/clevertap/android/sdk/utils/Clock.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/AnalyticsManagerTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/CleverTapAPITest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/CleverTapFactoryTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/EventQueueManagerTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/MockCoreState.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/MockDeviceInfo.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/TestClock.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/UtilsTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/events/EventMediatorTest.kt
  clevertap-core/src/test/java/com/clevertap/android/sdk/network/http/NetworkRepoTest.kt
Labels: Reviewed chained PRs
